name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main  # or the branch you want to test against

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub's hosted Ubuntu runner

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # No need for repository name

    - name: Set up .NET (if using .NET, adjust if needed)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.406'  # Specify the .NET version you're using

    - name: Install dependencies
      run: |
        dotnet restore  # or npm install, pip install, etc., depending on your stack

    - name: Run Tests
      run: |
        dotnet test  # Run your tests; adjust this to your test runner, e.g., npm test, pytest, etc.
